// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQa7s35YuYtbGEqFyJmnhMDHGqgzQdWDI',
    appId: '1:156582900159:web:425daf2de8dde38251f10a',
    messagingSenderId: '156582900159',
    projectId: 'saemosin',
    authDomain: 'saemosin.firebaseapp.com',
    storageBucket: 'saemosin.appspot.com',
    measurementId: 'G-WMEFFPMHN0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGO5FnPUgnDJYBV68vrMjsi3figGG5fEI',
    appId: '1:156582900159:android:63f43519c410a52051f10a',
    messagingSenderId: '156582900159',
    projectId: 'saemosin',
    storageBucket: 'saemosin.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyKgAiUNNB-9xTvMm1p7YEOjgAQz_7sY0',
    appId: '1:156582900159:ios:32c2ff0231f01d2651f10a',
    messagingSenderId: '156582900159',
    projectId: 'saemosin',
    storageBucket: 'saemosin.appspot.com',
    iosClientId: '156582900159-km3j79cnujes9luqojc8sp1vvhr89qp7.apps.googleusercontent.com',
    iosBundleId: 'com.example.semosin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyKgAiUNNB-9xTvMm1p7YEOjgAQz_7sY0',
    appId: '1:156582900159:ios:32c2ff0231f01d2651f10a',
    messagingSenderId: '156582900159',
    projectId: 'saemosin',
    storageBucket: 'saemosin.appspot.com',
    iosClientId: '156582900159-km3j79cnujes9luqojc8sp1vvhr89qp7.apps.googleusercontent.com',
    iosBundleId: 'com.example.semosin',
  );
}
