# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'administrator' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for administrator
  pod 'Charts'
  pod 'FirebaseAnalytics'
  pod 'FirebaseStorage'
  pod 'FirebaseFirestore'
  pod 'FirebaseAuth'

end
